In [2]:
#1b

import numpy as np

def y(a,b):
    y = 0
    for i in range(0,len(a)):
        y += a[i] * b[i]
    return print(y)

a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

y(a,b)


35


In [11]:
#1c

y = np.dot(a, b)
print(y)
y = a@b
print(y)

35
35


In [13]:
#1d
X = np.array([[1,2,3,4,5],[5,4,3,2,1],[1,3,5,7,9],[1,1,1,1,1]])

y = a@X.T

print(y)


[55 35 95 15]


In [16]:
#1e

a_tmp = np.tile(np.array([a]), (4,1)) #We tile the array a 4 times, so we can do elementwise multiplication
print(a_tmp)
y = np.sum(a_tmp*X, axis=1)
print(y)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[55 35 95 15]


In [19]:
#1f

Z = np.array([[4,4,4,4,4],
             [4,4,4,4,4],
             [4,4,4,4,4]])

print(Z.shape)
print(X.shape)
y = Z@X.T 
print(y)



(3, 5)
(4, 5)
[[ 60  60 100  20]
 [ 60  60 100  20]
 [ 60  60 100  20]]


In [20]:
#1g

#lik antall kolonne X og W

X = np.array([[1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1]])
W = np.array([
    [2,2,2,2,2,2],
    [2,2,2,2,2,2],
    [2,2,2,2,2,2]
])

a = np.array([3,3,3,3,3])

v = W@X.T
y = v@a
print(y)

[180 180 180]
