In [2]:
import numpy as np 

In [3]:
#Vectors
a = np.array([1,1,1,1,1,1])
b = np.array([2,2,2,2,2,2])
X = np.array([[3,3,3,3,3,3],
              [3,3,3,3,3,3],
              [3,3,3,3,3,3],
              [3,3,3,3,3,3]])
Z = np.array([[4,4,4,4,4,4],
             [4,4,4,4,4,4],
             [4,4,4,4,4,4]])

In [4]:
#Task 1b and 1c
'''
Vectorize the sum: y = sum(a_i*b_i)

Note that this sum is a simple vector product. 
For the NumPy package, matrix (and vector) products can be written as follows
'''
y = a@b
print(y)

12


In [5]:
#Task 1d
'''
We have a matrix X with dimensions NxM (4x6) and vector a with dimensions 1xM (1x6)
'''
y = a@X.T
print(y)

[18 18 18 18]


In [6]:
#Task 1e 
'''
We can't use matrix multiplication here, so we'll make it so we can do a simple elementwise multiplication
'''
a_tmp = np.tile(np.array([a]), (4,1))
y = np.sum(a_tmp*X, axis=1)
print(y)

[18 18 18 18]


In [7]:
#Task 1f
'''

'''
print(Z.shape)
print(X.shape)
y = Z@X.T 
print(y)


(3, 6)
(4, 6)
[[72 72 72 72]
 [72 72 72 72]
 [72 72 72 72]]


In [8]:
X = np.array([[1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1]])
W = np.array([
    [2,2,2,2,2,2],
    [2,2,2,2,2,2],
    [2,2,2,2,2,2]
])

a = np.array([3,3,3,3,3])


In [9]:
#Task 1g
'''

'''
v = W@X.T
y = v@a
print(y)

[180 180 180]


In [10]:
#Task 1h 
def matrix_multiply(matrix1, matrix2):
    ''' 
    Only works on two dimensional matrices (or lower maybe)
    '''
    
    # Get dimensions of the matrices
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)
    
    # Get dimensions of the matrices
    rows_matrix1 = matrix1.shape[0] # Number of rows in the first matrix
    cols_matrix1 = matrix1.shape[1]
    rows_matrix2 = matrix2.shape[0]
    cols_matrix2 = matrix2.shape[1]
    
    # Check if matrices can be multiplied
    if cols_matrix1 != rows_matrix2:
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix.")
    
    # Create result matrix with zeros
    result = np.zeros((rows_matrix1, cols_matrix2))
    
    # Perform matrix multiplication
    for i in range(rows_matrix1):
        for j in range(cols_matrix2):
            for k in range(cols_matrix1):  # or rows_matrix2
                result[i, j] += matrix1[i, k] * matrix2[k, j]
    
    return result

matrix1 = [
    [1, 2, 3],
    [4, 5, 6]
]

matrix2 = [
    [7, 8],
    [9, 10],
    [11, 12]
]

result = matrix_multiply(matrix1, matrix2)
print(f"Resultant Matrix: \n{result}")

Resultant Matrix: 
[[ 58.  64.]
 [139. 154.]]


Task 1i
$$(A^T A)^T = A^T (A^T)^T = A^T A$$

In [11]:
X = np.random.randint(low=0, high=10, size=(1000,5))
W = np.random.randint(low=0,high=10,size=(1,5))

import time 

start = time.time()
y = W@X.T
end=time.time()
print(end-start)

start = time.time()
y = matrix_multiply(X, W.T)
end=time.time()
print(end-start)


0.0
0.006734609603881836
